function renderSafetyActions(root,u){
  const arr=data.incidents.filter(i=>i.corrective).sort((a,b)=>new Date(b.corrective?.submittedAt||0)-new Date(a.corrective?.submittedAt||0));
  root.innerHTML=`<div class="panel"><div class="section-head"><div><div class="ey">CORRECTIVE REVIEW</div><h2>개선조치 검토</h2><p>현장에서 올린 원인·개선조치·완료사진을 검토하고 승인 또는 보완요청합니다.</p></div></div><div class="action-list">${arr.map(i=>`<div class="action-card"><div>${priorityBadge(i.priority)}${actionBadge(i)}</div><h3>${esc(siteById(i.siteId)?.name||'-')} · ${esc(i.eventType)}</h3><p>${esc(i.corrective.actionDetail||'')}</p><div class="action-grid"><div><b>담당자</b><span>${esc(i.corrective.ownerName||'-')}</span></div><div><b>완료기한</b><span>${esc(i.corrective.dueDate||'-')}</span></div><div><b>현장상태</b><span>${actionStatusName(i.corrective.status)}</span></div><div><b>사진</b><span>${i.corrective.afterPhotos?.length||0}장</span></div></div><button class="secondary" data-review-action="${i.id}">검토하기</button></div>`).join('')||'<div class="empty">등록된 개선조치가 없습니다.</div>'}</div></div>`;
  root.querySelectorAll('[data-review-action]').forEach(b=>b.onclick=()=>openActionReview(b.dataset.reviewAction,u));
}
function openActionReview(id,u){const i=data.incidents.find(x=>x.id===id);if(!i?.corrective)return;const c=i.corrective;openModal(`<div class="modal-head"><div><div class="ey">ACTION REVIEW</div><h2>${esc(siteById(i.siteId)?.name||'-')} 개선조치</h2></div><button class="x" data-close>×</button></div><div class="detail"><div class="detail-row"><b>사고내용</b><span>${esc(i.summary)}</span></div><div class="detail-row"><b>원인분석</b><span>${esc(c.rootCause||'-')}</span></div><div class="detail-row"><b>개선조치</b><span>${esc(c.actionDetail||'-')}</span></div><div class="detail-row"><b>담당/기한</b><span>${esc(c.ownerName||'-')} · ${esc(c.dueDate||'-')}</span></div></div>${c.afterPhotos?.length?`<div class="thumbs">${c.afterPhotos.map(p=>`<div class="thumb"><img src="${p}"></div>`).join('')}</div>`:''}<label class="lbl"><span>검토의견</span><textarea id="actionReviewNote" rows="3">${esc(c.reviewNote||'')}</textarea></label><div class="modal-actions"><button class="btn-gray" id="requestFix">보완요청</button><button class="btn-green" id="approveAction">조치 승인</button></div>`);document.getElementById('requestFix').onclick=()=>{c.status='in_progress';c.reviewNote=document.getElementById('actionReviewNote').value.trim()||'보완 후 다시 검토 요청해 주세요.';c.reviewedBy=u.name;c.reviewedAt=nowISO();saveData();closeModal();renderShell(u)};document.getElementById('approveAction').onclick=()=>{c.status='approved';c.reviewNote=document.getElementById('actionReviewNote').value.trim();c.reviewedBy=u.name;c.reviewedAt=nowISO();saveData();closeModal();renderShell(u)}}

function renderSites(root,u){
  root.innerHTML=`<div class="panel"><div class="section-head"><div><div class="ey">SITE MANAGEMENT</div><h2>현장관리</h2><p>현장소장 계정은 반드시 하나의 소속 사업장에 연결됩니다.</p></div></div><form id="siteAdd" style="display:flex;gap:7px;max-width:480px"><input id="newSiteName" placeholder="새 사업장명" required><button class="primary" style="white-space:nowrap">추가</button></form><div class="site-list">${data.sites.map(s=>`<div class="row-card"><div><b>${esc(s.name)}</b><br><span>사고 ${data.incidents.filter(i=>i.siteId===s.id).length}건 · 현장소장 ${data.users.filter(x=>x.role==='field'&&x.siteId===s.id&&x.active).length}명</span></div><div class="row-actions"><button class="small-btn red" data-del-site="${s.id}">삭제</button></div></div>`).join('')}</div></div>`;
  document.getElementById('siteAdd').onsubmit=e=>{e.preventDefault();const n=document.getElementById('newSiteName').value.trim();if(!n)return;if(data.sites.some(s=>s.name===n))return alert('같은 이름의 사업장이 있습니다.');data.sites.push({id:uid('site'),name:n});saveData();renderShell(u)};
  root.querySelectorAll('[data-del-site]').forEach(b=>b.onclick=()=>{const id=b.dataset.delSite;if(data.incidents.some(i=>i.siteId===id)||data.users.some(x=>x.siteId===id&&x.active))return alert('사고기록 또는 활성 사용자에 연결된 사업장은 삭제할 수 없습니다.');if(confirm('사업장을 삭제할까요?')){data.sites=data.sites.filter(s=>s.id!==id);saveData();renderShell(u)}})
}

function renderUsers(root,u){
  root.innerHTML=`<div class="panel"><div class="section-head"><div><div class="ey">USER MANAGEMENT</div><h2>사용자관리</h2><p>안전관리자만 계정을 생성·비활성화하고 역할 및 소속 현장을 지정할 수 있습니다.</p></div><button class="primary" id="addUserBtn">사용자 추가</button></div><div class="user-list">${data.users.map(x=>`<div class="row-card"><div><b>${esc(x.name)} ${x.active?'':'(비활성)'}</b><br><span>${esc(x.username)} · ${roleName(x.role)} · ${esc(siteById(x.siteId)?.name||'전체')}</span></div><div class="row-actions"><button class="small-btn" data-edit-user="${x.id}">수정</button>${x.id!==u.id?`<button class="small-btn ${x.active?'red':'green'}" data-toggle-user="${x.id}">${x.active?'비활성':'활성화'}</button>`:''}</div></div>`).join('')}</div></div>`;
  document.getElementById('addUserBtn').onclick=()=>openUserModal(null,u);root.querySelectorAll('[data-edit-user]').forEach(b=>b.onclick=()=>openUserModal(userById(b.dataset.editUser),u));root.querySelectorAll('[data-toggle-user]').forEach(b=>b.onclick=()=>{const x=userById(b.dataset.toggleUser);x.active=!x.active;saveData();renderShell(u)})
}
function openUserModal(user,u){const isNew=!user;openModal(`<div class="modal-head"><h2>${isNew?'사용자 추가':'사용자 수정'}</h2><button class="x" data-close>×</button></div><form id="userForm"><div class="formgrid"><label class="lbl"><span>이름</span><input id="uName" value="${esc(user?.name||'')}" required></label><label class="lbl"><span>로그인 아이디</span><input id="uLogin" value="${esc(user?.username||'')}" required ${isNew?'':'disabled'}></label><label class="lbl"><span>역할</span><select id="uRole"><option value="field" ${user?.role==='field'?'selected':''}>현장소장</option><option value="safety" ${user?.role==='safety'?'selected':''}>안전관리자</option><option value="final" ${user?.role==='final'?'selected':''}>최종관리자</option></select></label><label class="lbl"><span>소속 사업장</span><select id="uSite"><option value="">전체/해당없음</option>${data.sites.map(s=>`<option value="${s.id}" ${user?.siteId===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label></div>${isNew?'<label class="lbl"><span>초기 비밀번호</span><input id="uPw" type="password" minlength="4" required placeholder="4자 이상"></label>':'<div class="help" style="margin-top:12px">비밀번호는 해당 사용자가 우측 상단 계정 메뉴에서 직접 변경합니다.</div>'}<button class="primary full">저장</button></form>`);document.getElementById('userForm').onsubmit=async e=>{e.preventDefault();const role=document.getElementById('uRole').value,siteId=document.getElementById('uSite').value||null;if(role==='field'&&!siteId)return alert('현장소장은 소속 사업장을 반드시 지정해야 합니다.');if(isNew){const username=document.getElementById('uLogin').value.trim();if(data.users.some(x=>x.username===username))return alert('이미 사용하는 아이디입니다.');data.users.push({id:uid('u'),username,name:document.getElementById('uName').value.trim(),role,siteId:role==='field'?siteId:null,passwordHash:await sha256(document.getElementById('uPw').value),active:true,createdAt:nowISO()})}else{if(user.id===u.id&&role!=='safety')return alert('현재 로그인한 안전관리자 자신의 역할은 변경할 수 없습니다.');user.name=document.getElementById('uName').value.trim();user.role=role;user.siteId=role==='field'?siteId:null}saveData();closeModal();renderShell(u)}}

function renderFinalApproved(root,u){
  const arr=data.incidents.filter(i=>['approved','closed'].includes(i.status)).sort(sortIncidents);
  root.innerHTML=`<div class="panel"><div class="section-head"><div><div class="ey">EXECUTIVE VIEW</div><h2>승인 사고 조회</h2><p>안전관리자가 검토·승인한 사고만 표시됩니다. 읽기 전용입니다.</p></div></div>${incidentTable(arr,false)}</div>`;bindIncidentRows(false,u);
}

function openPasswordModal(){const u=currentUser();openModal(`<div class="modal-head"><h2>비밀번호 변경</h2><button class="x" data-close>×</button></div><form id="pwForm" class="pass-grid"><label class="lbl"><span>현재 비밀번호</span><input id="oldPw" type="password" required></label><label class="lbl"><span>새 비밀번호</span><input id="newPw" type="password" minlength="4" required></label><label class="lbl"><span>새 비밀번호 확인</span><input id="newPw2" type="password" minlength="4" required></label><button class="primary full">변경</button></form>`);document.getElementById('pwForm').onsubmit=async e=>{e.preventDefault();const oldH=await sha256(document.getElementById('oldPw').value),n=document.getElementById('newPw').value,n2=document.getElementById('newPw2').value;if(oldH!==u.passwordHash)return alert('현재 비밀번호가 맞지 않습니다.');if(n!==n2)return alert('새 비밀번호가 서로 다릅니다.');u.passwordHash=await sha256(n);saveData();closeModal();alert('비밀번호가 변경되었습니다.')}}
function openModal(html){const r=document.getElementById('modalRoot');r.innerHTML=`<div class="modal-bg"><div class="modal">${html}</div></div>`;r.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal);r.querySelector('.modal-bg').onclick=e=>{if(e.target===e.currentTarget)closeModal()}}
function closeModal(){const r=document.getElementById('modalRoot');if(r)r.innerHTML=''}

try{const bc=new BroadcastChannel('enl_safety_v3');bc.onmessage=()=>{data=loadData();render()}}catch(e){}
window.addEventListener('storage',e=>{if([DB_KEY,SESSION_KEY].includes(e.key)){data=loadData();session=loadSession();render()}});

render();
setTimeout(()=>{const u=currentUser();if(u?.role==='field'&&currentView==='report')renderFieldMini(u)},0);
