/* E&L Accident Report App v4.1.1 - authoritative person/property report flow */
(function(){
  'use strict';

  const VERSION='4.1.1-r11';
  let activeType=null;
  let activeEditId=null;

  const isSiteUser=u=>!!u&&['field','worker'].includes(u.role);
  const canCreate=u=>!!u&&['field','worker','safety'].includes(u.role);
  const value=id=>String(document.getElementById(id)?.value||'').trim();
  const money=v=>{const n=Number(String(v||'').replace(/,/g,''));return Number.isFinite(n)&&n>0?n:0};
  const moneyText=n=>n?`${n.toLocaleString('ko-KR')}원`:'미확인';
  const currentSiteName=id=>siteById?.(id)?.name||window.ENL_SITE_DIRECTORY?.find(s=>String(s.id)===String(id))?.name||'사업장';
  const activeEdit=()=>activeEditId?(data.incidents||[]).find(i=>String(i.id)===String(activeEditId)):null;
  const persistAttachment=a=>typeof window.enlPersistAttachment==='function'?window.enlPersistAttachment(a):a;
  const pad=n=>String(n).padStart(2,'0');
  const occurredParts=i=>{if(i?.occurredAt){const d=new Date(i.occurredAt);if(!Number.isNaN(d.getTime()))return {date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,time:`${pad(d.getHours())}:${pad(d.getMinutes())}`}}const dt=localDT();return {date:dt.slice(0,10),time:dt.slice(11,16)}};

  function backHome(u){activeType=null;activeEditId=null;if(isSiteUser(u)&&typeof window.enlFieldHome==='function')return window.enlFieldHome(u);currentView='home';renderShell(u)}
  function backRecords(u){activeType=null;activeEditId=null;currentView='incidents';renderShell(u)}
  function topBack(u,label='사고 종류 선택'){if(isSiteUser(u))return `<div class="field-task-back"><button type="button" data-report-home>← 현장 홈으로</button><span>${esc(currentSiteName(u.siteId))}</span></div>`;return `<div class="report410-top-back"><button type="button" data-report-home>← ${esc(label)}</button></div>`}
  function bindPicker(root,u){root.querySelector('[data-report-home]')?.addEventListener('click',()=>backHome(u));root.querySelectorAll('[data-report-type]').forEach(btn=>btn.addEventListener('click',()=>{activeEditId=null;activeType=btn.dataset.reportType;renderTypeForm(root,u,activeType,null)}))}
  function renderTypePicker(root,u){if(!root)return;activeType=null;activeEditId=null;root.innerHTML=`${topBack(u,'홈으로')}<section class="panel report-type-picker" data-report-picker="v410"><div class="section-head"><div><div class="ey">ACCIDENT REPORT</div><h2>사고 종류를 선택해 주세요</h2><p>발생한 사고에 맞는 경위서를 선택합니다.</p></div></div><div class="report-type-grid"><button type="button" class="report-type-card person" data-report-type="person"><span class="report-type-no">01</span><strong>대인사고</strong><small>사람이 다치거나 치료가 필요한 사고<br>부상·진단·진료비 중심 작성</small></button><button type="button" class="report-type-card property" data-report-type="property"><span class="report-type-no">02</span><strong>대물사고</strong><small>차량·장비·시설물이 파손된 사고<br>파손·복구견적 중심 작성</small></button></div><div class="report-type-note">사고 종류를 선택하면 해당 경위서에 필요한 항목만 표시됩니다.</div></section>`;bindPicker(root,u)}

  function siteControl(u,siteId){const selected=siteId||u?.siteId||'';if(isSiteUser(u))return `<input id="reportSite" type="hidden" value="${esc(selected)}"><input class="report410-overview-control" value="${esc(currentSiteName(selected))}" disabled>`;return `<select id="reportSite" class="report410-overview-control" required><option value="">사업장 선택</option>${(data.sites||[]).filter(s=>s.id!=='site-hq').map(s=>`<option value="${esc(s.id)}" ${String(s.id)===String(selected)?'selected':''}>${esc(s.name)}</option>`).join('')}</select>`}
  function commonTop(u,i){const dt=occurredParts(i),d=i?.reportDetails||{};return `<div class="report410-grid report410-overview-grid"><label class="lbl report410-overview-cell"><span>사업장 *</span>${siteControl(u,i?.siteId)}</label><label class="lbl report410-overview-cell"><span>발생 날짜 *</span><input class="report410-overview-control" id="occurredDate410" type="date" value="${esc(dt.date)}" required></label><label class="lbl report410-overview-cell"><span>발생 시간 *</span><input class="report410-overview-control" id="occurredTime410" type="time" value="${esc(dt.time)}" required></label><label class="lbl report410-wide"><span>정확한 사고 장소 *</span><input id="incidentPlace410" value="${esc(d.place||'')}" required placeholder="예: A코스 3홀 티 우측 법면부"></label><label class="lbl report410-wide"><span>사고 유형 *</span><select id="eventType">${eventTypeOptions(i?.eventType||'')}</select></label></div>`}
  function circumstanceSection(type,i){const d=i?.reportDetails||{},how=type==='person'?'예: 칡넝쿨 제거 작업 중 낫에 왼쪽 엄지손가락이 접촉하여 베임':'예: 작업차량 이동 중 홀맵지주 하단부와 접촉하여 찌그러짐',action=type==='person'?'예: 작업 중지 후 응급처치하고 병원으로 이동':'예: 작업 중지 후 파손부위 확인, 주변 통제 및 담당자 보고';return `<section class="report410-section"><div class="report410-section-head"><b>2. 사고 경위</b><small>사고 전 → 발생 → 사고 직후 순서로 작성합니다.</small></div><label class="lbl"><span>사고 직전에 무엇을 하고 있었나요? *</span><textarea id="workAction410" rows="2" required placeholder="예: K코스 2번홀 티 예지 작업을 하고 있었음">${esc(d.workAction||'')}</textarea></label><label class="lbl"><span>어떻게 사고가 발생했나요? *</span><textarea id="incidentHow410" rows="3" required placeholder="${how}">${esc(d.incidentHow||'')}</textarea></label><label class="lbl"><span>사고 직후 어떻게 조치했나요? *</span><textarea id="immediateAction" rows="3" required placeholder="${action}">${esc(i?.immediateAction||'')}</textarea></label></section>`}
  function causeSection(i){const d=i?.reportDetails||{};return `<section class="report410-section"><div class="report410-section-head"><b>3. 사고 원인</b><small>추측하지 말고 확인된 내용만 적어주세요. 아직 모르면 비워둘 수 있습니다.</small></div><label class="lbl"><span>환경적 요인</span><textarea id="environmentCause410" rows="2">${esc(d.environmentCause||'')}</textarea></label><label class="lbl"><span>행동적 요인</span><textarea id="behaviorCause410" rows="2">${esc(d.behaviorCause||'')}</textarea></label></section>`}
  function personDamageSection(i){const d=i?.reportDetails||{};return `<section class="report410-section report410-damage person"><div class="report410-section-head"><b>4. 대인 피해 상황</b><small>병원 진단 전이면 확인된 내용까지만 입력하세요.</small></div><div class="report410-grid"><label class="lbl"><span>피해 직원 성명 *</span><input id="injuredName" value="${esc(d.injuredName||i?.injuredName||'')}" required></label><label class="lbl"><span>직종 / 업무</span><input id="job" value="${esc(d.job||i?.job||'')}"></label><label class="lbl report410-wide"><span>어디를 어떻게 다쳤나요? *</span><textarea id="injuryDetail410" rows="3" required>${esc(d.injuryDetail||'')}</textarea></label><label class="lbl report410-wide"><span>진단명</span><input id="diagnosis410" value="${esc(d.diagnosis||'')}"></label><label class="lbl report410-wide"><span>의사 소견 / 치료 예상기간</span><textarea id="doctorOpinion410" rows="2">${esc(d.doctorOpinion||'')}</textarea></label><label class="lbl"><span>진료비(현재 확인금액)</span><input id="medicalCost410" type="number" min="0" inputmode="numeric" value="${esc(d.medicalCost||'')}"></label><label class="lbl"><span>치료 / 휴업 예상</span><select id="leaveEstimate"><option value="unknown">미확인</option><option value="none">휴업 없음</option><option value="under3">3일 미만 예상</option><option value="3plus">3일 이상 예상</option><option value="longterm">장기치료 / 중상 가능</option></select></label><label class="lbl report410-wide"><span>진료비 상세내역</span><textarea id="medicalCostDetail410" rows="2">${esc(d.medicalCostDetail||'')}</textarea></label></div></section>`}
  function propertyDamageSection(i){const d=i?.reportDetails||{};return `<section class="report410-section report410-damage property"><div class="report410-section-head"><b>4. 대물 피해 상황 및 복구 견적</b><small>견적이 아직 없으면 피해내용만 먼저 입력하세요.</small></div><div class="report410-grid"><label class="lbl"><span>작업자 성명</span><input id="propertyWorker410" value="${esc(d.workerName||'')}"></label><label class="lbl"><span>직종 / 업무</span><input id="job" value="${esc(d.job||i?.job||'')}"></label><label class="lbl report410-wide"><span>파손된 물품 / 시설 *</span><input id="damagedItem410" value="${esc(d.damagedItem||'')}" required></label><label class="lbl report410-wide"><span>어떻게 파손되었나요? *</span><textarea id="damageDetail410" rows="3" required>${esc(d.damageDetail||'')}</textarea></label><label class="lbl"><span>복구 예상 비용</span><input id="repairCost410" type="number" min="0" inputmode="numeric" value="${esc(d.repairCost||'')}"></label><label class="lbl report410-wide"><span>견적 / 비용 상세내역</span><textarea id="repairCostDetail410" rows="3">${esc(d.repairCostDetail||'')}</textarea></label></div></section>`}
  function closingSection(type,i,u){const d=i?.reportDetails||{},manual=String(i?.prioritySource||'')==='manual'?i?.priority:'auto';return `<section class="report410-section"><div class="report410-section-head"><b>5. 재발 방지 및 관리</b><small>구체적인 예방조치를 입력합니다.</small></div><label class="lbl"><span>재발 방지 대책 *</span><textarea id="preventionPlan410" rows="3" required>${esc(d.preventionPlan||'')}</textarea></label><label class="lbl"><span>특이사항</span><textarea id="specialNote410" rows="2">${esc(d.specialNote||'')}</textarea></label><div class="report410-grid report410-risk-grid"><label class="lbl"><span>${type==='person'?'부상 정도':'피해 정도'}</span><select id="severity"><option value="minor">경미</option><option value="moderate">보통</option><option value="major">중대</option></select></label><label class="report410-check"><input id="potentialMajor" type="checkbox"><span>현재 피해가 작아도 큰 사고로 이어질 가능성이 있었음</span></label>${u?.role==='safety'?`<label class="lbl report410-wide"><span>관리등급</span><select id="priorityManual411"><option value="auto" ${manual==='auto'?'selected':''}>자동 추천</option><option value="normal" ${manual==='normal'?'selected':''}>일반</option><option value="important" ${manual==='important'?'selected':''}>중요</option><option value="urgent" ${manual==='urgent'?'selected':''}>긴급</option></select><small style="margin-top:5px;color:#6b7e90">자동 추천값을 참고하되 안전관리자가 최종 등급을 직접 지정할 수 있습니다.</small></label>`:''}</div></section>`}

  function renderTypeForm(root,u,type,i=activeEdit()){
    if(!root)return;if(!['person','property'].includes(type))return renderTypePicker(root,u);activeType=type;
    const person=type==='person',editing=!!i,title=person?'대인사고 경위서':'대물사고 경위서',desc=person?'부상·진단·진료비 등 인적 피해 중심으로 작성합니다.':'파손내용·복구비용·견적 등 물적 피해 중심으로 작성합니다.';
    root.innerHTML=`${topBack(u)}<form id="unifiedReportForm" class="panel report-simple incident410-form" data-report-type="${type}" data-editing="${editing?'true':'false'}"><div class="section-head"><div><div class="ey">${person?'PERSON INCIDENT':'PROPERTY INCIDENT'}</div><h2>${title}${editing?' 수정':''}</h2><p>${editing?'기존에 입력한 내용을 불러왔습니다. 필요한 부분을 수정한 뒤 다시 제출해 주세요.':desc}</p></div>${editing?'<button type="button" class="secondary report410-change" data-cancel-edit>← 사고 기록으로</button>':'<button type="button" class="secondary report410-change" data-change-type>← 사고 종류 변경</button>'}</div><section class="report410-section"><div class="report410-section-head"><b>1. 사고 개요</b><small>언제, 어디서 발생했는지 입력합니다.</small></div>${commonTop(u,i)}</section>${circumstanceSection(type,i)}${causeSection(i)}${person?personDamageSection(i):propertyDamageSection(i)}${closingSection(type,i,u)}<section class="report410-section report410-photo"><div class="report410-section-head"><b>6. 현장사진 · PDF *</b><small>사진 또는 관련 PDF 자료를 등록할 수 있습니다.</small></div>${photoPickerHtml('incident')}</section><button class="primary full report410-submit" type="submit">${editing?'수정 후 다시 제출':title+' 제출하기'}</button></form>`;
    incidentPhotos=editing&&Array.isArray(i.photos)?[...i.photos]:[];renderPhotoThumbs('incident');bindPhotoButtons();
    if(person){const leave=document.getElementById('leaveEstimate');if(leave)leave.value=i?.leaveEstimate||'unknown'}
    const severity=document.getElementById('severity');if(severity)severity.value=i?.severity||'minor';const potential=document.getElementById('potentialMajor');if(potential)potential.checked=!!i?.potentialMajor;
    root.querySelector('[data-report-home]')?.addEventListener('click',()=>backHome(u));root.querySelector('[data-change-type]')?.addEventListener('click',()=>renderTypePicker(root,u));root.querySelector('[data-cancel-edit]')?.addEventListener('click',()=>backRecords(u));root.querySelector('#unifiedReportForm')?.addEventListener('submit',e=>submitIncident410(e,u,type,i));
  }

  function required(id,label){const el=document.getElementById(id);if(el&&String(el.value||'').trim())return true;el?.focus();el?.scrollIntoView({behavior:'smooth',block:'center'});alert(`${label}을(를) 입력해 주세요.`);return false}
  function formatOccurred(date,time){if(!date)return '';const p=date.split('-');return p.length===3?`${Number(p[0])}년 ${Number(p[1])}월 ${Number(p[2])}일 ${time||''}경`.trim():`${date} ${time}`.trim()}
  function buildSummary(type,siteId){const when=formatOccurred(value('occurredDate410'),value('occurredTime410')),site=currentSiteName(siteId),place=value('incidentPlace410'),work=value('workAction410'),how=value('incidentHow410'),env=value('environmentCause410'),behavior=value('behaviorCause410'),prevention=value('preventionPlan410'),special=value('specialNote410'),cause=[env&&`환경적 요인: ${env}`,behavior&&`행동적 요인: ${behavior}`].filter(Boolean).join(' / ');let damage='';if(type==='person'){const cost=money(value('medicalCost410'));damage=[`${value('injuredName')||'피해 직원'}: ${value('injuryDetail410')}`,value('diagnosis410')&&`진단명: ${value('diagnosis410')}`,value('doctorOpinion410')&&`의사 소견: ${value('doctorOpinion410')}`,cost&&`진료비: ${moneyText(cost)}`].filter(Boolean).join(' / ')}else{const cost=money(value('repairCost410'));damage=[value('propertyWorker410')&&`작업자: ${value('propertyWorker410')}`,`${value('damagedItem410')}: ${value('damageDetail410')}`,cost&&`복구 예상비용: ${moneyText(cost)}`].filter(Boolean).join(' / ')}return [`[사고 개요] ${when} ${site} ${place}`,`[사고 경위] ${work} 중 ${how}`,cause&&`[사고 원인] ${cause}`,`[피해 상황] ${damage}`,`[재발 방지 대책] ${prevention}`,special&&`[특이사항] ${special}`].filter(Boolean).join('  ')}

  async function submitIncident410(e,u,type,existing=null){
    e.preventDefault();if(!canCreate(u))return alert('사고보고 등록 권한이 없습니다.');
    for(const [id,label] of [['reportSite','사업장'],['occurredDate410','발생 날짜'],['occurredTime410','발생 시간'],['incidentPlace410','사고 장소'],['workAction410','사고 직전 작업'],['incidentHow410','사고 발생 과정'],['immediateAction','사고 직후 조치'],['preventionPlan410','재발 방지 대책']])if(!required(id,label))return;
    if(type==='person'){if(!required('injuredName','피해 직원 성명')||!required('injuryDetail410','부상 내용'))return}else if(!required('damagedItem410','파손된 물품 또는 시설')||!required('damageDetail410','파손 내용'))return;
    if(!Array.isArray(incidentPhotos)||incidentPhotos.length<1){document.querySelector('.report410-photo')?.scrollIntoView({behavior:'smooth',block:'center'});return alert('현장사진 또는 PDF 파일을 1개 이상 등록해 주세요.')}
    if(existing&&typeof window.enlCanEditIncident==='function'&&!window.enlCanEditIncident(existing,u))return alert('현재 상태에서는 이 사고보고를 수정할 수 없습니다.');
    const siteId=value('reportSite'),date=value('occurredDate410'),time=value('occurredTime410'),severity=value('severity')||'minor',leaveEstimate=type==='person'?(value('leaveEstimate')||'unknown'):'none',potentialMajor=!!document.getElementById('potentialMajor')?.checked,summary=buildSummary(type,siteId),eventType=value('eventType'),autoPriority=computePriority(type,severity,eventType,potentialMajor,leaveEstimate),priorityChoice=u?.role==='safety'?(value('priorityManual411')||'auto'):'auto',priority=priorityChoice==='auto'?autoPriority:priorityChoice,prioritySource=priorityChoice==='auto'?'auto':'manual',details={templateVersion:'v411',reportType:type,place:value('incidentPlace410'),workAction:value('workAction410'),incidentHow:value('incidentHow410'),environmentCause:value('environmentCause410'),behaviorCause:value('behaviorCause410'),preventionPlan:value('preventionPlan410'),specialNote:value('specialNote410'),generatedSummary:summary,recordedAt:nowISO()};
    if(type==='person')Object.assign(details,{injuredName:value('injuredName'),job:value('job'),injuryDetail:value('injuryDetail410'),diagnosis:value('diagnosis410'),doctorOpinion:value('doctorOpinion410'),medicalCost:money(value('medicalCost410')),medicalCostDetail:value('medicalCostDetail410')});else Object.assign(details,{workerName:value('propertyWorker410'),job:value('job'),damagedItem:value('damagedItem410'),damageDetail:value('damageDetail410'),repairCost:money(value('repairCost410')),repairCostDetail:value('repairCostDetail410')});
    const common={siteId,category:type,eventType,severity,leaveEstimate,potentialMajor,injuredName:type==='person'?value('injuredName'):'',job:value('job'),summary,immediateAction:value('immediateAction'),photos:[...incidentPhotos].map(persistAttachment),occurredAt:new Date(`${date}T${time}`).toISOString(),updatedAt:nowISO(),priority,prioritySource,prioritySetBy:prioritySource==='manual'?u.name:'',prioritySetAt:prioritySource==='manual'?nowISO():null,legalReview:computeLegalReview(type,severity,leaveEstimate),reportDetails:details};
    if(existing){const previousStatus=existing.status;Object.assign(existing,common);existing.status='reported';existing.resubmittedBy=u.name;existing.resubmittedById=u.personnelId||u.id||'';existing.resubmittedAt=nowISO();existing.reviewHistory=Array.isArray(existing.reviewHistory)?existing.reviewHistory:[];existing.reviewHistory.push({action:previousStatus==='reported'?'withdrawn_and_resubmitted':'resubmitted',by:u.name,at:existing.resubmittedAt});saveData();incidentPhotos=[];activeType=null;activeEditId=null;alert('수정된 사고보고서가 다시 제출되었습니다.');currentView='incidents';return renderShell(u)}
    const incident={id:uid('inc'),...common,reporterName:u.name,reporterId:u.personnelId||u.id||'',createdAt:nowISO(),status:'reported',safetyNote:'',approvedBy:'',approvedAt:null,closedAt:null,corrective:null,readReceipts:[]};data.incidents.unshift(incident);saveData();incidentPhotos=[];activeType=null;activeEditId=null;alert(`${type==='person'?'대인사고':'대물사고'} 경위서가 접수되었습니다.`);currentView='incidents';renderShell(u)
  }

  function renderReport(root,u){if(!root)return;if(!canCreate(u)){root.innerHTML='<div class="panel permission-empty"><div class="lock-icon">🔒</div><h2>사고보고 등록 권한이 없습니다.</h2></div>';return}const edit=activeEdit();if(edit){activeType=edit.category;return renderTypeForm(root,u,activeType,edit)}if(activeType)return renderTypeForm(root,u,activeType,null);return renderTypePicker(root,u)}
  window.renderUnifiedReport=renderReport;window.submitUnifiedIncident=submitIncident410;
  window.enlResetIncidentReport=()=>{activeType=null;activeEditId=null};
  window.enlShowIncidentTypePicker=(u=currentUser?.())=>{activeType=null;activeEditId=null;currentView='report';const root=document.getElementById('view');if(root)return renderTypePicker(root,u)};
  window.enlOpenIncidentReport=(type,u=currentUser?.())=>{const root=document.getElementById('view');if(!root)return;activeEditId=null;activeType=type;return renderTypeForm(root,u,type,null)};
  window.enlEditIncidentInReportForm=(incidentOrId,u=currentUser?.())=>{const i=typeof incidentOrId==='object'?incidentOrId:(data.incidents||[]).find(x=>String(x.id)===String(incidentOrId));if(!i)return alert('사고기록을 찾지 못했습니다.');if(!['person','property'].includes(i.category))return alert('대인·대물 사고보고만 원래 입력화면에서 수정할 수 있습니다.');if(typeof window.enlCanEditIncident==='function'&&!window.enlCanEditIncident(i,u))return alert('현재 상태에서는 이 사고보고를 수정할 수 없습니다.');activeEditId=i.id;activeType=i.category;currentView='report';return renderShell(u)};
  window.ENL_REPORT_VERSION=VERSION;
})();