import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.5";

const cors={"Access-Control-Allow-Origin":"https://enlsafety.github.io","Access-Control-Allow-Headers":"content-type, x-client-info, apikey, authorization, x-enl-app","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
const clean=(v:any)=>String(v??"").trim();
const norm=(v:any)=>clean(v).replace(/\s+/g,"").toLocaleLowerCase("ko-KR");
const nonneg=(v:any)=>Math.max(0,Math.trunc(Number(v)||0));
function safeIncident(x:any){if(!x||typeof x!=="object")return null;const id=clean(x.id),siteId=clean(x.siteId);if(!id||!siteId)return null;return {...x,id,siteId};}
function actorFrom(body:any){const a=body?.actor||{};return {id:clean(a.id),name:clean(a.name)||"사용자",role:clean(a.role||body?.role),position:clean(a.position),siteId:clean(a.siteId||body?.siteId)};}
const scoped=(r:string)=>r==="field"||r==="worker";
const timeOf=(x:any)=>{const n=new Date(x?.updatedAt||x?.createdAt||0).getTime();return Number.isFinite(n)?n:0;};
function preserveWorkflow(prev:any,next:any,role:string){if(!prev||!["worker","field","final"].includes(role))return next;const out={...next};for(const k of ["status","approvedBy","approvedAt","closedAt","safetyNote","legalReview"]){if(k in prev)out[k]=prev[k];}if(prev.corrective&&out.corrective){out.corrective={...out.corrective,reviewNote:prev.corrective.reviewNote||"",reviewedBy:prev.corrective.reviewedBy||"",reviewedAt:prev.corrective.reviewedAt||null};if(prev.corrective.status==="approved")out.corrective.status="approved";}return out;}
async function hashText(v:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("");}
function phonePin(v:any){const d=clean(v).replace(/\D/g,"");return d.length>=4?d.slice(-4):"";}

Deno.serve(async(req:Request)=>{
  if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
  if(req.method!=="POST")return json({ok:false,message:"method_not_allowed"},405);
  const origin=req.headers.get("origin")||"";if(origin&&origin!=="https://enlsafety.github.io")return json({ok:false,message:"origin_not_allowed"},403);
  if(req.headers.get("x-enl-app")!=="incident-report-v2")return json({ok:false,message:"invalid_client"},403);
  const dbUrl=Deno.env.get("SUPABASE_DB_URL")||"";if(!dbUrl)return json({ok:false,message:"server_not_configured"},500);
  let body:any={};try{body=await req.json();}catch(_){return json({ok:false,message:"invalid_json"},400);}
  const action=clean(body?.action),actor=actorFrom(body),role=actor.role,siteId=actor.siteId||clean(body?.siteId),now=new Date().toISOString();
  const sql=postgres(dbUrl,{prepare:false,max:4,connect_timeout:5,idle_timeout:2});
  try{
    async function siteNamesMap(){const rows=await sql`select site_id,site_name from public.enl_site_master where active=true`;return new Map(rows.map((x:any)=>[x.site_id,x.site_name]));}
    async function syncSiteRoles(saved:any,prev:any=null){const sid=clean(saved?.site_id);if(!sid)return;const defs=[{title:"현장소장",nameKey:"manager_name",phoneKey:"manager_phone"},{title:"파트장",nameKey:"part_name",phoneKey:"part_phone"},{title:"서무",nameKey:"clerk_name",phoneKey:"clerk_phone"}];let people=await sql`select * from public.enl_site_personnel where site_id=${sid}`;for(const d of defs){const oldName=clean(prev?.[d.nameKey]),newName=clean(saved?.[d.nameKey]),pin=phonePin(saved?.[d.phoneKey]);if(oldName&&norm(oldName)!==norm(newName)){const old=people.find((x:any)=>norm(x.name)===norm(oldName)&&clean(x.job_title)===d.title);if(old)await sql`update public.enl_site_personnel set active=false,updated_at=${now},updated_by_id=${actor.id},updated_by_name=${actor.name},updated_by_role=${role},updated_by_position=${actor.position} where personnel_id=${old.personnel_id}`;}if(!newName)continue;let found=people.find((x:any)=>norm(x.name)===norm(newName));const pinHash=pin?await hashText(pin):clean(found?.pin_hash);if(found){const rows=await sql`update public.enl_site_personnel set site_id=${sid},name=${newName},job_title=${d.title},access_role='field',active=true,pin_hash=${pinHash||null},updated_at=${now},updated_by_id=${actor.id},updated_by_name=${actor.name},updated_by_role=${role},updated_by_position=${actor.position},source=${found.source||"site-master"} where personnel_id=${found.personnel_id} returning *`;people=people.map((x:any)=>x.personnel_id===rows[0]?.personnel_id?rows[0]:x);}else if(pinHash){const rows=await sql`insert into public.enl_site_personnel(site_id,name,job_title,active,created_at,updated_at,updated_by_id,updated_by_name,updated_by_role,updated_by_position,access_role,pin_hash,source) values(${sid},${newName},${d.title},true,${now},${now},${actor.id},${actor.name},${role},${actor.position},'field',${pinHash},'site-master') returning *`;if(rows[0])people.push(rows[0]);}}}

    if(action==="site_directory"){const rows=await sql`select site_id,site_name,region,active from public.enl_site_master where active=true order by site_name`;return json({ok:true,sites:rows});}
    if(action==="site_seed"){
      if(role!=="safety")return json({ok:false,message:"forbidden"},403);const incoming=Array.isArray(body?.sites)?body.sites:[];const existing=await sql`select site_id from public.enl_site_master`;const have=new Set(existing.map((x:any)=>x.site_id));let created=0;for(const s of incoming){const sid=clean(s?.site_id);if(!sid||have.has(sid))continue;const reg=nonneg(s?.regular_count),daily=nonneg(s?.daily_count);const row:any={site_id:sid,site_name:clean(s?.site_name)||sid,source_site_name:clean(s?.source_site_name),site_type:clean(s?.site_type),region:clean(s?.region),start_date:clean(s?.start_date),address:clean(s?.address),regular_count:reg,daily_count:daily,total_count:reg+daily,headcount_basis:clean(s?.headcount_basis),manager_name:clean(s?.manager_name),manager_phone:clean(s?.manager_phone),part_name:clean(s?.part_name),part_phone:clean(s?.part_phone),clerk_name:clean(s?.clerk_name),clerk_phone:clean(s?.clerk_phone),safety_outsource_status:clean(s?.safety_outsource_status),safety_agency:clean(s?.safety_agency),agency_manager:clean(s?.agency_manager),agency_phone:clean(s?.agency_phone),contract_period:clean(s?.contract_period),inspection_cycle:clean(s?.inspection_cycle),course_holes:clean(s?.course_holes),work_pattern:clean(s?.work_pattern),agency_scope:clean(s?.agency_scope),agency_note:clean(s?.agency_note),verification_note:clean(s?.verification_note),needs_verification:!!s?.needs_verification,source:clean(s?.source)||"seed",active:true,created_at:now,updated_at:now,updated_by_id:actor.id,updated_by_name:actor.name,updated_by_role:role,updated_by_position:actor.position};const rows=await sql`insert into public.enl_site_master ${sql(row)} returning *`;created++;have.add(sid);await syncSiteRoles(rows[0],null);}return json({ok:true,created});
    }
    if(action==="site_list"){
      if(role!=="safety")return json({ok:false,message:"forbidden"},403);const sites=await sql`select * from public.enl_site_master order by active desc,site_name`;const people=await sql`select site_id,access_role,active from public.enl_site_personnel`;const count=new Map<string,{workers:number,field:number}>();for(const p of people){if(!p.active)continue;const c=count.get(p.site_id)||{workers:0,field:0};if(p.access_role==="worker")c.workers++;if(p.access_role==="field")c.field++;count.set(p.site_id,c);}return json({ok:true,sites:sites.map((s:any)=>({...s,worker_login_count:count.get(s.site_id)?.workers||0,field_login_count:count.get(s.site_id)?.field||0}))});
    }
    if(action==="site_upsert"){
      if(role!=="safety")return json({ok:false,message:"forbidden"},403);const p=body?.site||{};let sid=clean(p.site_id);if(!sid)sid=`site-${crypto.randomUUID()}`;const rr=await sql`select * from public.enl_site_master where site_id=${sid} limit 1`,prev=rr[0]||null,reg=nonneg(p.regular_count),daily=nonneg(p.daily_count);const row:any={site_id:sid,site_name:clean(p.site_name)||sid,source_site_name:clean(p.source_site_name||prev?.source_site_name),site_type:clean(p.site_type),region:clean(p.region),start_date:Object.prototype.hasOwnProperty.call(p,"contract_end_date")?clean(p.start_date):(clean(p.start_date)||prev?.start_date||""),contract_end_date:Object.prototype.hasOwnProperty.call(p,"contract_end_date")?clean(p.contract_end_date):prev?.contract_end_date||null,address:clean(p.address),regular_count:reg,daily_count:daily,total_count:reg+daily,headcount_basis:clean(p.headcount_basis||prev?.headcount_basis),manager_name:clean(p.manager_name),manager_phone:clean(p.manager_phone),part_name:clean(p.part_name),part_phone:clean(p.part_phone),clerk_name:clean(p.clerk_name),clerk_phone:clean(p.clerk_phone),safety_outsource_status:clean(p.safety_outsource_status),safety_agency:clean(p.safety_agency),agency_manager:clean(p.agency_manager),agency_phone:clean(p.agency_phone),contract_period:clean(p.contract_period),inspection_cycle:clean(p.inspection_cycle),course_holes:clean(p.course_holes),work_pattern:clean(p.work_pattern),agency_scope:clean(p.agency_scope),agency_note:clean(p.agency_note),verification_note:clean(p.verification_note),needs_verification:!!p.needs_verification,source:clean(p.source||prev?.source)||"manual",active:p.active!==false,created_at:prev?.created_at||now,updated_at:now,updated_by_id:actor.id,updated_by_name:actor.name,updated_by_role:role,updated_by_position:actor.position};let rows:any[];if(prev){const cols=Object.keys(row).filter(k=>!['site_id','created_at'].includes(k));rows=await sql`update public.enl_site_master set ${sql(row,...cols)} where site_id=${sid} returning *`;}else rows=await sql`insert into public.enl_site_master ${sql(row)} returning *`;const saved=rows[0];await sql`insert into public.enl_site_audit(site_id,action,editor_id,editor_name,editor_role,editor_position,changed_at,before_payload,after_payload) values(${sid},${prev?"update":"create"},${actor.id},${actor.name},${role},${actor.position},${now},${prev?JSON.stringify(prev):null}::jsonb,${JSON.stringify(saved)}::jsonb)`;if(!prev||["manager_name","manager_phone","part_name","part_phone","clerk_name","clerk_phone"].some(k=>clean(saved?.[k])!==clean(prev?.[k])))await syncSiteRoles(saved,prev);return json({ok:true,site:saved});
    }
    if(action==="site_audit_pull"){
      if(role!=="safety")return json({ok:false,message:"forbidden"},403);const sid=clean(body?.siteId);const rows=sid?await sql`select audit_id,site_id,action,editor_id,editor_name,editor_role,editor_position,changed_at from public.enl_site_audit where site_id=${sid} order by changed_at desc limit 50`:await sql`select audit_id,site_id,action,editor_id,editor_name,editor_role,editor_position,changed_at from public.enl_site_audit order by changed_at desc limit 50`;return json({ok:true,audit:rows});
    }
    if(action==="manager_seed"){
      const managers=Array.isArray(body?.managers)?body.managers:[];let created=0,updated=0;for(const m of managers){const sid=clean(m?.siteId),name=clean(m?.name),position=clean(m?.position),pinHash=clean(m?.pinHash);if(!sid||!name||!pinHash)continue;const list=await sql`select * from public.enl_site_personnel where site_id=${sid}`,prev=list.find((x:any)=>norm(x.name)===norm(name));if(prev){const active=prev.source==="legacy"?m.active!==false:prev.active;await sql`update public.enl_site_personnel set access_role='field',pin_hash=${pinHash},job_title=${position||prev.job_title},source=${prev.source||"legacy"},active=${active},updated_at=${now} where personnel_id=${prev.personnel_id}`;updated++;}else{await sql`insert into public.enl_site_personnel(site_id,name,job_title,active,access_role,pin_hash,source,created_at,updated_at) values(${sid},${name},${position},${m.active!==false},'field',${pinHash},'legacy',${now},${now})`;created++;}}return json({ok:true,created,updated});
    }
    if(action==="personnel_lookup"){
      const name=clean(body?.name),accessRole=clean(body?.accessRole);if(!name)return json({ok:false,message:"name_required"},400);let rows=accessRole==="worker"||accessRole==="field"?await sql`select personnel_id,site_id,name,job_title,access_role,active from public.enl_site_personnel where active=true and access_role=${accessRole}`:await sql`select personnel_id,site_id,name,job_title,access_role,active from public.enl_site_personnel where active=true`;const names=await siteNamesMap();const people=rows.filter((x:any)=>norm(x.name)===norm(name)).map((x:any)=>({...x,site_name:names.get(x.site_id)||x.site_id}));return json({ok:true,people});
    }
    if(action==="worker_login"){
      const sid=clean(body?.siteId),name=clean(body?.name);if(!sid||!name)return json({ok:false,message:"input_required"},400);const rows=await sql`select personnel_id,site_id,name,job_title,access_role,active from public.enl_site_personnel where site_id=${sid} and active=true and access_role='worker'`;const person=rows.find((x:any)=>norm(x.name)===norm(name));if(!person)return json({ok:false,message:"worker_not_found"},404);const names=await siteNamesMap();return json({ok:true,person:{...person,site_name:names.get(person.site_id)||person.site_id}});
    }
    if(action==="manager_login"){
      const sid=clean(body?.siteId),name=clean(body?.name),pinHash=clean(body?.pinHash);if(!sid||!name||!pinHash)return json({ok:false,message:"input_required"},400);const rows=await sql`select personnel_id,site_id,name,job_title,access_role,active,pin_hash from public.enl_site_personnel where site_id=${sid} and active=true and access_role='field' and pin_hash=${pinHash}`;const person=rows.find((x:any)=>norm(x.name)===norm(name));if(!person)return json({ok:false,message:"manager_not_found"},404);const names=await siteNamesMap();return json({ok:true,person:{personnel_id:person.personnel_id,site_id:person.site_id,site_name:names.get(person.site_id)||person.site_id,name:person.name,job_title:person.job_title,access_role:person.access_role,active:person.active}});
    }
    if(action==="personnel_pull"){
      const sid=clean(body?.siteId);if(!sid)return json({ok:false,message:"site_required"},400);const canInactive=(role==="field"&&siteId===sid)||role==="safety";const rows=canInactive?await sql`select personnel_id,site_id,name,job_title,access_role,active,created_at,updated_at,updated_by_name,updated_by_role,updated_by_position from public.enl_site_personnel where site_id=${sid} order by active desc,name`:await sql`select personnel_id,site_id,name,job_title,access_role,active,created_at,updated_at,updated_by_name,updated_by_role,updated_by_position from public.enl_site_personnel where site_id=${sid} and active=true order by active desc,name`;return json({ok:true,personnel:rows});
    }
    if(action==="personnel_upsert"){
      if(!["field","safety"].includes(role))return json({ok:false,message:"forbidden"},403);const p=body?.person||{},sid=clean(p.siteId||body?.siteId),name=clean(p.name),jobTitle=clean(p.jobTitle),accessRole=clean(p.accessRole)==="field"?"field":"worker",pinHash=clean(p.pinHash),active=p.active!==false;if(!sid||!name)return json({ok:false,message:"invalid_personnel"},400);if(role==="field"&&siteId!==sid)return json({ok:false,message:"site_forbidden"},403);const list=await sql`select * from public.enl_site_personnel where site_id=${sid}`,targetId=clean(p.personnelId),prev=list.find((x:any)=>targetId?String(x.personnel_id)===targetId:norm(x.name)===norm(name));if(accessRole==="field"&&!pinHash&&!prev?.pin_hash)return json({ok:false,message:"pin_required"},400);const finalPin=accessRole==="worker"?null:(pinHash||prev?.pin_hash||null),source=prev?.source||"manual";let rows:any[];if(prev)rows=await sql`update public.enl_site_personnel set site_id=${sid},name=${name},job_title=${jobTitle},access_role=${accessRole},active=${active},pin_hash=${finalPin},updated_at=${now},updated_by_id=${actor.id},updated_by_name=${actor.name},updated_by_role=${role},updated_by_position=${actor.position},source=${source} where personnel_id=${prev.personnel_id} returning *`;else rows=await sql`insert into public.enl_site_personnel(site_id,name,job_title,access_role,active,pin_hash,source,created_at,updated_at,updated_by_id,updated_by_name,updated_by_role,updated_by_position) values(${sid},${name},${jobTitle},${accessRole},${active},${finalPin},${source},${now},${now},${actor.id},${actor.name},${role},${actor.position}) returning *`;const saved=rows[0],auditAction=!prev?"create":prev.active&&!active?"retire":!prev.active&&active?"reactivate":"update";await sql`insert into public.enl_personnel_audit(personnel_id,site_id,action,editor_id,editor_name,editor_role,editor_position,changed_at,before_payload,after_payload) values(${saved.personnel_id},${sid},${auditAction},${actor.id},${actor.name},${role},${actor.position},${now},${prev?JSON.stringify(prev):null}::jsonb,${JSON.stringify(saved)}::jsonb)`;return json({ok:true,person:{...saved,pin_hash:undefined}});
    }
    if(action==="audit_pull"){
      if(!["field","safety","final"].includes(role))return json({ok:false,message:"forbidden"},403);const incidentId=clean(body?.incidentId);let rows:any[];if(role==="field")rows=incidentId?await sql`select audit_id,incident_id,site_id,action,editor_id,editor_name,editor_role,editor_position,changed_at from public.enl_incident_audit where incident_id=${incidentId} and site_id=${siteId} order by changed_at desc limit 30`:await sql`select audit_id,incident_id,site_id,action,editor_id,editor_name,editor_role,editor_position,changed_at from public.enl_incident_audit where site_id=${siteId} order by changed_at desc limit 30`;else rows=incidentId?await sql`select audit_id,incident_id,site_id,action,editor_id,editor_name,editor_role,editor_position,changed_at from public.enl_incident_audit where incident_id=${incidentId} order by changed_at desc limit 30`:await sql`select audit_id,incident_id,site_id,action,editor_id,editor_name,editor_role,editor_position,changed_at from public.enl_incident_audit order by changed_at desc limit 30`;return json({ok:true,audit:rows});
    }
    if(action==="push"){
      if(!["worker","field","safety","final"].includes(role))return json({ok:false,message:"forbidden"},403);let incoming=(Array.isArray(body?.incidents)?body.incidents:[]).map(safeIncident).filter(Boolean) as any[];if(scoped(role))incoming=incoming.filter((i:any)=>siteId&&i.siteId===siteId);const ids=incoming.map((i:any)=>i.id);const existing=ids.length?await sql`select incident_id,site_id,payload from public.enl_incident_shared where incident_id in ${sql(ids)}`:[];const old=new Map(existing.map((r:any)=>[r.incident_id,r]));let pushed=0,ignored=0;for(const raw of incoming){const prevRow=old.get(raw.id),prev=prevRow?.payload||null;if(prev&&timeOf(raw)<=timeOf(prev)){ignored++;continue;}let next=preserveWorkflow(prev,{...raw},role);if(!prev){next.reporterName=clean(next.reporterName)||actor.name;next.reporterId=clean(next.reporterId)||actor.id;if(role!=="safety"){next.status="reported";next.safetyNote="";next.approvedBy="";next.approvedAt=null;next.closedAt=null;}}else{next.reporterName=prev.reporterName||next.reporterName||actor.name;next.reporterId=prev.reporterId||next.reporterId||actor.id;}const prevCorr=JSON.stringify(prev?.corrective||null),nextCorr=JSON.stringify(next?.corrective||null);if(next.corrective&&prevCorr!==nextCorr)next.corrective={...next.corrective,lastModifiedBy:actor.name,lastModifiedRole:role,lastModifiedPosition:actor.position,lastModifiedAt:now,submittedBy:next.corrective.submittedBy||actor.name};next.lastModifiedBy=actor.name;next.lastModifiedRole=role;next.lastModifiedPosition=actor.position||(role==="worker"?"일반근로자":"");next.lastModifiedAt=now;next.updatedAt=now;const saved=await sql`insert into public.enl_incident_shared(incident_id,site_id,payload,created_at,updated_at) values(${next.id},${next.siteId},${JSON.stringify(next)}::jsonb,${prevRow?.created_at||now},${now}) on conflict(incident_id) do update set site_id=excluded.site_id,payload=excluded.payload,updated_at=excluded.updated_at returning payload`;await sql`insert into public.enl_incident_audit(incident_id,site_id,action,editor_id,editor_name,editor_role,editor_position,changed_at,before_payload,after_payload) values(${next.id},${next.siteId},${prev?"update":"create"},${actor.id},${actor.name},${role},${actor.position},${now},${prev?JSON.stringify(prev):null}::jsonb,${JSON.stringify(saved[0]?.payload||next)}::jsonb)`;pushed++;}
      let deleted=0;const deletedIds=(Array.isArray(body?.deletedIds)?body.deletedIds:[]).map(clean).filter(Boolean);if(deletedIds.length&&role==="safety"){const toDelete=await sql`select incident_id,site_id,payload from public.enl_incident_shared where incident_id in ${sql(deletedIds)}`;for(const r of toDelete)await sql`insert into public.enl_incident_audit(incident_id,site_id,action,editor_id,editor_name,editor_role,editor_position,changed_at,before_payload,after_payload) values(${r.incident_id},${r.site_id},'delete',${actor.id},${actor.name},${role},${actor.position},${now},${JSON.stringify(r.payload)}::jsonb,null)`;await sql`delete from public.enl_incident_shared where incident_id in ${sql(deletedIds)}`;deleted=deletedIds.length;}return json({ok:true,pushed,ignored,deleted});
    }
    if(action==="pull"){
      if(!["worker","field","safety","final"].includes(role))return json({ok:false,message:"forbidden"},403);let rows:any[];if(scoped(role)){if(!siteId)return json({ok:false,message:"site_required"},400);rows=await sql`select payload,updated_at from public.enl_incident_shared where site_id=${siteId} order by updated_at desc`;}else rows=await sql`select payload,updated_at from public.enl_incident_shared order by updated_at desc`;return json({ok:true,incidents:rows.map((r:any)=>r.payload)});
    }
    return json({ok:false,message:"invalid_action"},400);
  }catch(e:any){const m=String(e?.message||e);return json({ok:false,message:m},m.includes("enl_sync_conflict")?409:500)}finally{await sql.end({timeout:1}).catch(()=>{})}
});
