import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=path.join(root,'ai/qa/artifacts');fs.mkdirSync(out,{recursive:true});
const agents=['incident_manager','legal_reviewer','final_auditor','safety_director'],stamp=new Date().toISOString(),id='10000000-0000-4000-8000-000000000001';
const source={title:'산업안전보건법 · 공식 근거',url:'https://www.law.go.kr/법령/산업안전보건법',source_type:'법령'};
function fixture(){const workflow={id,source_id:'test-incident',input_summary:'QA 가상사업장 · 이동 중 미끄러짐 사고 검토',status:'running',priority:'urgent',current_agent:agents[1],created_at:stamp,started_at:stamp,requires_human_approval:true,step_index:1};const runs=agents.map((a,i)=>({id:'run-'+i,workflow_id:id,agent_id:a,status:i===0?'completed':i===1?'running':'queued',created_at:stamp,started_at:i<2?stamp:null,completed_at:i===0?stamp:null,result_summary:i===0?'사고 사실 구조화 완료':null,output_payload:{missing_information:['휴업일수 확인 필요'],official_sources:i===1?[source]:[],_meta:{usage:i===0?{input_tokens:123,output_tokens:45,total_tokens:168}:null}}}));const events=agents.slice(0,2).map((a,i)=>({id:'event-'+i,workflow_id:id,agent_run_id:'run-'+i,agent_id:a,event_type:i?'source_search_started':'completed',title:i?'공식 법령자료 검색 시작':'사고 사실 구조화 완료',status:i?'checking_sources':'completed',progress:i?20:100,created_at:stamp}));return {workflow,runs,events,findings:[{agent_id:agents[2],finding_type:'contradiction',severity:'medium',title:'검토 의견 차이',detail:'휴업일수 확인 전 법적 결론 확정 금지'}],approvals:[]};}
for(const [engine,width] of (process.env.QA_LIFECYCLE?[[webkit,390]]:process.env.QA_NARROW?[[webkit,320]]:[[chromium,1440],[chromium,390],[webkit,390],[webkit,320]])){
 const browser=await engine.launch({headless:true});const context=await browser.newContext({viewport:{width,height:1000},serviceWorkers:'block'});const page=await context.newPage();let state=fixture(),polls=0,decisions=[],requests=[],offline=false,intentionalNetworkFailures=0;const errors=[];page.on('pageerror',e=>{if(intentionalNetworkFailures>0&&e.message==='/zgwxzfvvpqgdedyobwmg.supabase.co/functions/v1/enl-ai-safety-v440 due to access control checks.'){intentionalNetworkFailures--;return;}errors.push(e.message);});
 if(process.env.QA_LIFECYCLE)await page.addInitScript(()=>{Object.defineProperty(navigator,'standalone',{get:()=>true});window.qaHidden=false;Object.defineProperty(document,'hidden',{get:()=>window.qaHidden});});
 await page.route('**/*',async route=>{const url=new URL(route.request().url());
  if(url.hostname==='zgwxzfvvpqgdedyobwmg.supabase.co'){if(offline){intentionalNetworkFailures++;return route.abort();}const body=route.request().postDataJSON();requests.push(body.action);let r={ok:true};if(body.action==='control_room'){polls++;r={...r,workflows:[state.workflow],runs:state.runs,events:state.events};}else if(body.action==='get_workflow')r={...r,...state};else if(['review_incident','review_question'].includes(body.action)){assert(body.requestId);assert.equal(body.incidentSnapshot,undefined);r.workflowId=id;}else if(body.action==='decide_workflow'){decisions.push(body.decision);state.workflow.status=body.decision==='held'?'on_hold':body.decision==='approved'?'completed':'queued';r.workflowId=id;}else if(body.action==='retry_workflow'){decisions.push('retry');state.workflow.status='queued';r.workflowId=id;}return route.fulfill({json:r,headers:{'Access-Control-Allow-Origin':'*'}});}
  if(url.hostname!=='127.0.0.1')return route.abort();
  if(url.pathname==='/harness'){return route.fulfill({contentType:'text/html',body:`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial,sans-serif;margin:16px}button,select,textarea{font:inherit}</style><main id="view"></main><script>var currentView='ai-team';var user={id:'qa',role:'safety',passwordHash:'unit-test-only'};var currentUser=()=>user;var data={incidents:[{id:'test-incident',siteId:'qa',summary:'가상 사고'}]};var siteById=()=>({name:'가상사업장'});window.enlCurrentActor=()=>user;window.renderNav=()=>'<nav></nav>';window.renderCurrentView=()=>document.getElementById('view').innerHTML='<p>기존 화면</p>';</script><script src="/ai-safety-team-v440.js"></script><script>renderCurrentView(user)</script></html>`});}
  const file=path.join(root,decodeURIComponent(url.pathname));if(!file.startsWith(root)||!fs.existsSync(file))return route.fulfill({status:404,body:''});return route.fulfill({contentType:file.endsWith('.js')?'application/javascript; charset=utf-8':file.endsWith('.css')?'text/css':'text/html',body:fs.readFileSync(file)});
 });
 await page.goto('http://127.0.0.1:8729/harness');await page.locator('.ai440-seat').first().waitFor();assert.equal(await page.locator('.ai440-seat').count(),4);await page.getByText('자동 갱신 · 3초',{exact:false}).waitFor({timeout:6000}).catch(async e=>{console.log(await page.locator('body').innerText(),errors);throw e;});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,`${engine.name()}-${width}-room.png`),fullPage:true});
 if(process.env.QA_LIFECYCLE){
  await page.evaluate(()=>window.qaSeat=document.querySelector('.ai440-seat'));state.events=Array.from({length:35},(_,i)=>({...state.events[0],id:'scroll-'+i,title:'스크롤 보존 검증 '+i}));await page.waitForTimeout(3300);
  assert(await page.evaluate(()=>window.qaSeat===document.querySelector('.ai440-seat')),'poll replaced card');
  const before=await page.evaluate(()=>{const el=document.querySelector('.ai440-timeline');el.scrollTop=220;const a=[...el.children].find(n=>n.getBoundingClientRect().top>=el.getBoundingClientRect().top);window.qaAnchor=a;return a.getBoundingClientRect().top;});
  state.events.unshift({...state.events[0],id:'new-top',title:'새 이벤트'});await page.waitForTimeout(3300);assert(Math.abs(await page.evaluate(()=>window.qaAnchor.getBoundingClientRect().top)-before)<3,'timeline jumped');
  const calls=requests.filter(x=>x.startsWith('review_')).length;await page.evaluate(()=>{window.qaHidden=true;document.dispatchEvent(new Event('visibilitychange'));});await page.waitForTimeout(500);await page.evaluate(()=>{window.qaHidden=false;document.dispatchEvent(new Event('visibilitychange'));});
  offline=true;await page.waitForTimeout(3700);await page.locator('.ai440-connection.stale').waitFor();assert.equal(await page.locator('.ai440-seat').count(),4);offline=false;await page.locator('.ai440-connection:not(.stale)').waitFor({timeout:15000});assert.equal(requests.filter(x=>x.startsWith('review_')).length,calls);
  await page.reload();await page.locator('.ai440-seat').first().waitFor();assert.equal(await page.locator('.ai440-seat').count(),4);
 }
 await page.locator('[data-agent="legal_reviewer"]').click();await page.getByRole('dialog').waitFor();assert(await page.getByRole('dialog').getByText('법령검토 상세').count());assert(await page.getByRole('dialog').locator('a').count());await page.getByRole('button',{name:'닫기',exact:true}).click();
 state.workflow.status='awaiting_approval';state.runs.forEach(r=>{r.status='completed';r.completed_at=stamp;});state.workflow.completed_at=stamp;await page.waitForTimeout(3300);
 await page.locator('#ai440WorkflowList [data-workflow]').click();await page.locator('#ai440DecisionNote').fill('검토 메모 유지');await page.waitForTimeout(3300);assert.equal(await page.locator('#ai440DecisionNote').inputValue(),'검토 메모 유지');assert(await page.getByText('의견 충돌 감지 · 사용자 확인 필요').count());
 assert(await page.evaluate(()=>[...document.querySelectorAll('.ai440-modal button')].filter(x=>x.offsetParent).every(x=>{const r=x.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;})));
 await page.screenshot({path:path.join(out,`${engine.name()}-${width}-detail.png`),fullPage:true});
 if(process.env.QA_LIFECYCLE){for(const viewport of [{width:844,height:390},{width:390,height:500},{width:390,height:844}]){await page.setViewportSize(viewport);await page.locator('#ai440DecisionNote').focus();await page.waitForTimeout(3300);assert.equal(await page.locator('#ai440DecisionNote').inputValue(),'검토 메모 유지');assert(await page.locator('#ai440DecisionNote').evaluate(n=>n===document.activeElement));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.getByRole('dialog').evaluate(n=>{const r=n.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}));await page.screenshot({path:path.join(out,`webkit-lifecycle-${viewport.width}-${viewport.height}.png`)});}}
 await page.getByRole('button',{name:'보류',exact:true}).click();await page.getByRole('button',{name:'승인',exact:true}).waitFor();await page.getByRole('button',{name:'승인',exact:true}).click();await page.waitForTimeout(300);assert.deepEqual(decisions,['held','approved']);await page.getByRole('button',{name:'닫기',exact:true}).click();
 state.workflow.status='failed';state.runs[1].status='failed';state.runs[1].error_message='AI 서비스 오류';await page.waitForTimeout(3300);await page.locator('#ai440WorkflowList [data-workflow]').click();await page.getByRole('button',{name:'실패 업무 재시도'}).click();await page.waitForTimeout(300);assert(decisions.includes('retry'));await page.getByRole('button',{name:'닫기',exact:true}).click();
 await page.getByRole('tab',{name:'업무지시/검토'}).click();await page.locator('#ai440Incident').selectOption('test-incident');await page.getByRole('button',{name:'검토 시작',exact:true}).click();await page.getByRole('dialog').waitFor();assert(requests.includes('review_incident'));
 await page.getByRole('button',{name:'닫기',exact:true}).click();await page.getByRole('tab',{name:'업무지시/검토'}).click();await page.locator('#ai440Incident').selectOption('');await page.locator('#ai440Question').fill('우리 사업장 안전관리자는 몇 명 선임해야 하나요?');await page.getByRole('button',{name:'검토 시작',exact:true}).dblclick();await page.getByRole('dialog').waitFor();assert.equal(requests.filter(x=>x==='review_question').length,1);
 await page.evaluate(()=>{user={id:'worker',role:'worker'};currentView='home';renderCurrentView(user);});assert.equal(await page.locator('.ai440-modal').count(),0);const count=polls;await page.waitForTimeout(3300);assert.equal(polls,count);assert.deepEqual(errors,[]);
 console.log(`PASS: ${engine.name()} ${width}px cards, live polling, modal, official links, note retention, hold/approve/retry, async review, logout cleanup, overflow`);
 if(process.env.QA_LIFECYCLE)console.log('PASS: WebKit emulated standalone flag, portrait/landscape/keyboard-height, DOM identity, timeline anchor, focus, reload, visibility return, API offline recovery. No physical iPhone or installed PWA tested.');
 await browser.close();
}



