import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const {chromium,webkit}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=path.join(root,'ai/qa/artifacts');fs.mkdirSync(out,{recursive:true});
const agents=['incident_manager','legal_reviewer','final_auditor','safety_director'],stamp=new Date().toISOString(),id='10000000-0000-4000-8000-000000000001';
const source={title:'산업안전보건법 · 공식 근거',url:'https://www.law.go.kr/법령/산업안전보건법',source_type:'법령'};
function fixture(){const workflow={id,source_id:'test-incident',input_summary:'QA 가상사업장 · 이동 중 미끄러짐 사고 검토',status:'running',priority:'urgent',current_agent:agents[1],created_at:stamp,started_at:stamp,requires_human_approval:true,step_index:1};const runs=agents.map((a,i)=>({id:'run-'+i,workflow_id:id,agent_id:a,status:i===0?'completed':i===1?'running':'queued',created_at:stamp,started_at:i<2?stamp:null,completed_at:i===0?stamp:null,result_summary:i===0?'사고 사실 구조화 완료':null,output_payload:{missing_information:['휴업일수 확인 필요'],official_sources:i===1?[source]:[],_meta:{usage:i===0?{input_tokens:123,output_tokens:45,total_tokens:168}:null}}}));const events=agents.slice(0,2).map((a,i)=>({id:'event-'+i,workflow_id:id,agent_run_id:'run-'+i,agent_id:a,event_type:i?'source_search_started':'completed',title:i?'공식 법령자료 검색 시작':'사고 사실 구조화 완료',status:i?'checking_sources':'completed',progress:i?20:100,created_at:stamp}));return {workflow,runs,events,findings:[{agent_id:agents[2],finding_type:'contradiction',severity:'medium',title:'검토 의견 차이',detail:'휴업일수 확인 전 법적 결론 확정 금지'}],approvals:[]};}
for(const [engine,width] of (process.env.QA_NARROW?[[webkit,320]]:[[chromium,1440],[chromium,390],[webkit,390],[webkit,320]])){
 const browser=await engine.launch({headless:true});const context=await browser.newContext({viewport:{width,height:1000},serviceWorkers:'block'});const page=await context.newPage();let state=fixture(),polls=0,decisions=[],requests=[];const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{const url=new URL(route.request().url());
  if(url.hostname==='zgwxzfvvpqgdedyobwmg.supabase.co'){const body=route.request().postDataJSON();requests.push(body.action);let r={ok:true};if(body.action==='control_room'){polls++;r={...r,workflows:[state.workflow],runs:state.runs,events:state.events};}else if(body.action==='get_workflow')r={...r,...state};else if(body.action==='review_incident'){assert(body.requestId);assert.equal(body.incidentSnapshot,undefined);r.workflowId=id;}else if(body.action==='decide_workflow'){decisions.push(body.decision);state.workflow.status=body.decision==='held'?'on_hold':body.decision==='approved'?'completed':'queued';r.workflowId=id;}else if(body.action==='retry_workflow'){decisions.push('retry');state.workflow.status='queued';r.workflowId=id;}return route.fulfill({json:r,headers:{'Access-Control-Allow-Origin':'*'}});}
  if(url.hostname!=='127.0.0.1')return route.abort();
  if(url.pathname==='/harness'){return route.fulfill({contentType:'text/html',body:`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:Arial,sans-serif;margin:16px}button,select,textarea{font:inherit}</style><main id="view"></main><script>var currentView='ai-team';var user={id:'qa',role:'safety',passwordHash:'unit-test-only'};var currentUser=()=>user;var data={incidents:[{id:'test-incident',siteId:'qa',summary:'가상 사고'}]};var siteById=()=>({name:'가상사업장'});window.enlCurrentActor=()=>user;window.renderNav=()=>'<nav></nav>';window.renderCurrentView=()=>document.getElementById('view').innerHTML='<p>기존 화면</p>';</script><script src="/ai-safety-team-v440.js"></script><script>renderCurrentView(user)</script></html>`});}
  const file=path.join(root,decodeURIComponent(url.pathname));if(!file.startsWith(root)||!fs.existsSync(file))return route.fulfill({status:404,body:''});return route.fulfill({contentType:file.endsWith('.js')?'application/javascript; charset=utf-8':file.endsWith('.css')?'text/css':'text/html',body:fs.readFileSync(file)});
 });
 await page.goto('http://127.0.0.1:8729/harness');await page.locator('.ai440-seat').first().waitFor();assert.equal(await page.locator('.ai440-seat').count(),4);await page.getByText('자동 갱신 · 3초',{exact:false}).waitFor({timeout:6000}).catch(async e=>{console.log(await page.locator('body').innerText(),errors);throw e;});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(out,`${engine.name()}-${width}-room.png`),fullPage:true});
 await page.locator('[data-agent="legal_reviewer"]').click();await page.getByRole('dialog').waitFor();assert(await page.getByRole('dialog').getByText('법령검토 상세').count());assert(await page.getByRole('dialog').locator('a').count());await page.getByRole('button',{name:'닫기',exact:true}).click();
 state.workflow.status='awaiting_approval';state.runs.forEach(r=>{r.status='completed';r.completed_at=stamp;});state.workflow.completed_at=stamp;await page.waitForTimeout(3300);
 await page.locator('#ai440WorkflowList [data-workflow]').click();await page.locator('#ai440DecisionNote').fill('검토 메모 유지');await page.waitForTimeout(3300);assert.equal(await page.locator('#ai440DecisionNote').inputValue(),'검토 메모 유지');assert(await page.getByText('의견 충돌 감지 · 사용자 확인 필요').count());
 assert(await page.evaluate(()=>[...document.querySelectorAll('.ai440-modal button')].filter(x=>x.offsetParent).every(x=>{const r=x.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;})));
 await page.screenshot({path:path.join(out,`${engine.name()}-${width}-detail.png`),fullPage:true});
 await page.getByRole('button',{name:'보류',exact:true}).click();await page.getByRole('button',{name:'승인',exact:true}).waitFor();await page.getByRole('button',{name:'승인',exact:true}).click();await page.waitForTimeout(300);assert.deepEqual(decisions,['held','approved']);await page.getByRole('button',{name:'닫기',exact:true}).click();
 state.workflow.status='failed';state.runs[1].status='failed';state.runs[1].error_message='AI 서비스 오류';await page.waitForTimeout(3300);await page.locator('#ai440WorkflowList [data-workflow]').click();await page.getByRole('button',{name:'실패 업무 재시도'}).click();await page.waitForTimeout(300);assert(decisions.includes('retry'));await page.getByRole('button',{name:'닫기',exact:true}).click();
 await page.getByRole('tab',{name:'업무지시/검토'}).click();await page.locator('#ai440Incident').selectOption('test-incident');await page.getByRole('button',{name:'검토 시작',exact:true}).click();await page.getByRole('dialog').waitFor();assert(requests.includes('review_incident'));
 await page.evaluate(()=>{user={id:'worker',role:'worker'};currentView='home';renderCurrentView(user);});assert.equal(await page.locator('.ai440-modal').count(),0);const count=polls;await page.waitForTimeout(3300);assert.equal(polls,count);assert.deepEqual(errors,[]);
 console.log(`PASS: ${engine.name()} ${width}px cards, live polling, modal, official links, note retention, hold/approve/retry, async review, logout cleanup, overflow`);
 await browser.close();
}



