import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {stripTypeScriptTypes} from 'node:module';
let source=fs.readFileSync(new URL('../edge/enl-ai-safety-v440/index.ts',import.meta.url),'utf8').replace(/^import .*;\r?\n/gm,'');
source+='\nglobalThis.testAPI={extractText,officialUrl,minimized,normalizeResult,publicError,callAgent,internalValid};';
let outgoing,reply;
const sandbox={Deno:{env:{get:key=>key==='OPENAI_API_KEY'?'unit-test-only':undefined},serve:()=>{}},crypto:globalThis.crypto,TextEncoder,TextDecoder,URL,Date,AbortController,AbortSignal,setTimeout,clearTimeout,atob,btoa,fetch:async(url,options)=>{outgoing=JSON.parse(options.body);return {ok:true,json:async()=>reply};},EdgeRuntime:{waitUntil:()=>{}}};
vm.createContext(sandbox);vm.runInContext(stripTypeScriptTypes(source),sandbox);const a=sandbox.testAPI;
assert.equal(a.extractText({output:[{type:'reasoning',content:[{text:'PRIVATE REASONING'}]},{type:'message',content:[{text:'PUBLIC'}]}]}),'PUBLIC');
for(const u of ['javascript:alert(1)','https://law.go.kr.evil.test','http://law.go.kr','https://user:pass@law.go.kr'])assert.equal(a.officialUrl(u),false);
assert.equal(a.officialUrl('https://www.law.go.kr/법령/산업안전보건법'),true);
const redacted=a.minimized({victimName:'홍테스트',summary:'홍테스트 연락 010-1234-5678 test@example.com',password:'never',photos:['private'],name:'관리자'});
assert(!JSON.stringify(redacted).includes('홍테스트'));assert(!JSON.stringify(redacted).includes('010-'));assert(!JSON.stringify(redacted).includes('never'));assert(!('photos' in redacted));
assert.equal(a.publicError(Error('API SECRET VALUE')),'검토 결과를 저장하거나 처리하지 못했습니다. 재시도해 주세요.');
assert.match(a.publicError(Error('openai_insufficient_quota')),/사용 한도/);
assert.equal(await a.internalValid({workflowId:'bad'}),false);
const result={summary:'검토',facts:[],findings:[],missing_information:[],official_sources:[{title:'검증됨',url:'https://law.go.kr/verified',source_type:'법령'},{title:'미검증',url:'https://law.go.kr/invented',source_type:'법령'}],confidence:.8,recommended_disposition:'human_review',private_reasoning:'DO NOT SAVE'};
reply={id:'resp-test',model:'test',usage:{input_tokens:100,output_tokens:50,total_tokens:150},output:[{type:'reasoning',content:[{text:'DO NOT SAVE'}]},{type:'web_search_call',action:{sources:[{url:'https://law.go.kr/verified'}]}},{type:'message',content:[{text:JSON.stringify(result)}]}]};
const response=await a.callAgent({name:'legal_reviewer',model:'test',instructions:'test',input:{},web:true});
assert.equal(outgoing.store,false);assert.equal(outgoing.tool_choice,'required');assert(outgoing.include.includes('web_search_call.action.sources'));assert.equal(response.result.official_sources.length,1);assert(!JSON.stringify(response.result).includes('DO NOT SAVE'));assert.equal(response.usage.total_tokens,150);
console.log('PASS: Edge output privacy, source verification, HTTPS allowlist, PII minimization, real usage and signed worker rejection');
