// Optional staging read-only UI QA with an explicitly provisioned temporary safety account.
// Credentials stay in memory and are never included in artifacts or console output.
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const q=JSON.parse(fs.readFileSync(process.env.ENL_QA_CREDENTIAL_FILE));const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000},serviceWorkers:'block'});
await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname==='zgwxzfvvpqgdedyobwmg.supabase.co')return route.continue();if(u.hostname==='127.0.0.1')return route.fulfill({contentType:'text/html; charset=utf-8',body:'<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><body style="font-family:Arial,sans-serif;margin:16px"><main id="view"></main></body></html>'});return route.abort();});
await page.goto('http://127.0.0.1:8729/qa-live');await page.evaluate(q=>{window.currentView='ai-team';window.currentUser=()=>({id:q.id,role:'safety',passwordHash:q.credential});window.enlCurrentActor=window.currentUser;window.data={incidents:[]};window.renderNav=()=>'<nav></nav>';window.renderCurrentView=()=>{};},q);
await page.addScriptTag({content:fs.readFileSync(path.join(root,'ai-safety-team-v440.js'),'utf8')});await page.evaluate(()=>window.enlRenderAiSafetyTeam(document.getElementById('view')));await page.getByText('자동 갱신 · 3초',{exact:false}).waitFor();assert.equal(await page.locator('.ai440-seat').count(),4);
const out=path.join(root,'ai/qa/artifacts');fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,'staging-live-room.png'),fullPage:true});await page.locator('#ai440WorkflowList button').first().click();await page.getByRole('button',{name:'실패 업무 재시도'}).waitFor();await page.screenshot({path:path.join(out,'staging-live-failure.png'),fullPage:true});console.log('PASS: real staging safety login, stored event polling, workflow detail and failed-workflow retry control visible');await browser.close();
