// Focused real-shell menu integration; all remote calls are mocked.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const browser=await chromium.launch({headless:true}),page=await browser.newPage();const errors=[],calls=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.hostname!=='127.0.0.1'){const b=route.request().postDataJSON();calls.push(b?.action);return route.fulfill({json:{ok:true,users:[],sites:[],incidents:[],workflows:[],runs:[],events:[],epoch:1},headers:{'Access-Control-Allow-Origin':'*'}});}const file=path.join(root,u.pathname);return route.fulfill({contentType:file.endsWith('.js')?'application/javascript; charset=utf-8':file.endsWith('.css')?'text/css':'text/html; charset=utf-8',body:fs.readFileSync(file)});});
await page.goto('http://127.0.0.1:8729/stable412.html');await page.evaluate(()=>{session={manager:{id:'qa',name:'메뉴검증',role:'safety',passwordHash:'fixture-only'}};currentView='home';renderShell(currentUser());});
const menu=page.locator('.shell411-nav [data-shell-view="ai-team"]');await menu.waitFor();assert.equal(await menu.count(),1);await menu.click();await page.getByRole('heading',{name:'AI 안전관리본부 상황실'}).waitFor();await page.getByRole('tab',{name:'업무지시/검토'}).click();await page.locator('#ai440Question').waitFor({state:'visible'});
await page.locator('[data-shell-view="home"]').click();assert.equal(await page.locator('.ai440').count(),0);
await page.evaluate(()=>{session={manager:{id:'qa-other',name:'권한검증',role:'manager'}};currentView='home';renderShell(currentUser());});assert.equal(await page.locator('[data-shell-view="ai-team"]').count(),0);assert(!calls.some(x=>['review_question','review_incident','process_step'].includes(x)));assert.deepEqual(errors,[]);
console.log('PASS: actual rendered shell shows one safety menu; click opens control room and question input; home return and manager exclusion; no AI request sent.');await browser.close();
