-- ERP handoff v1: isolated document references only; NO modification of incident payload.
-- Run on a test project first. Dedicated Edge Function checks active HQ safety user and password proof.
create table if not exists public.enl_erp_document_links (
  incident_id text primary key references public.enl_incident_shared(incident_id) on delete restrict,
  site_id text not null,
  erp_document_no text not null check (char_length(btrim(erp_document_no)) between 1 and 80 and erp_document_no !~ '[[:cntrl:]<>]'),
  erp_status text not null check (erp_status in ('submitted','approved')),
  revision integer not null default 1 check (revision >= 1),
  created_by text not null,
  created_at timestamptz not null default now(),
  updated_by text not null,
  updated_at timestamptz not null default now()
);
create index if not exists enl_erp_document_links_site_idx
  on public.enl_erp_document_links(site_id,updated_at desc);

create table if not exists public.enl_erp_document_link_audit (
  id bigint generated by default as identity primary key,
  incident_id text not null references public.enl_incident_shared(incident_id) on delete restrict,
  before_document_no text,
  before_status text,
  after_document_no text not null,
  after_status text not null check (after_status in ('submitted','approved')),
  revision integer not null check (revision >= 1),
  changed_by text not null,
  changed_at timestamptz not null default now()
);
create index if not exists enl_erp_document_link_audit_lookup
  on public.enl_erp_document_link_audit(incident_id,changed_at desc);

alter table public.enl_erp_document_links enable row level security;
alter table public.enl_erp_document_link_audit enable row level security;
revoke all on table public.enl_erp_document_links, public.enl_erp_document_link_audit from public, anon, authenticated;
revoke all on sequence public.enl_erp_document_link_audit_id_seq from public, anon, authenticated;
-- Deliberately no RLS allow policies: only the private, authenticated Edge Function accesses these tables.
